### ISSUE TITLE
Simulator freezes on loading error

### ISSUE THREAD

**Issue by jakebeal** [DanySK/alchemist#12]
Errors encountered while loading a scenario file cause the Alchemist app to freeze up entirely.

**Comment by DanySK** [comment]
Hi, can you attach an XML to reproduce, or write a sequence of steps to take?

Also, launching the simulator from the shell (see [this page][UI]) and pasting the output may turn useful.

[UI]: https://danysk.github.io/alchemist/pages/tutorial/swingui/

**Comment by jakebeal** [comment]
The specific place I've seen it happen is when I mistype the name of a map file.
So, to reproduce, try taking a known-good map-based simulation, then breaking the map file name.
It might be map-specific, or it might be a general failure --- I do not know.

**Comment by DanySK** [comment]
That issue with the map not existing was supposed to be fixed in 1.1.0: I guess you have already tried and it still stands - I'll take a look.

**Comment by DanySK** [comment]
Solved in mainline
