### ISSUE TITLE
Visualization should be specifiable by human-editable text

### ISSUE THREAD

**Issue by jakebeal** [DanySK/alchemist#14]
Visualization specs should be able to be specified efficiently by editing a text file (e.g., XML or JSON), not only as a serialization from a slow by-hand process through the Alchemist GUI.

**Comment by DanySK** [comment]
Alchemist 2.0.0 supports a -g command flag, that takes as input an Alchemist Effect Stack file.
Along with the other command line options, that should solve this issue.

I am marking this as closed, please reopen if the implementation is unsatisfactory (documentation will follow shortly).
