### ISSUE TITLE
Better zooming

### ISSUE THREAD

**Issue by jakebeal** [DanySK/alchemist#8]
Scroll-to-zoom is extremely hast and jerky (at least with maps), such that it is essentially useless for me: it should either be throttled to be less sensitive or else there should be "zoom in/ zoom out" buttons to allow movement one stage at a time.

**Comment by DanySK** [comment]
This has been dealt with by relying on the Mapsforge visualization machinery: we do not have direct control of the zooming level anymore - at least when using maps.
